using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SceneParser.Enumerators
{
    public enum Location {
        Bizarro_BattleCenter                             = 0x0001,
        Grassland                                        = 0x0002,
        Mt_Nibel                                         = 0x0003,
        Forest                                           = 0x0004,
        Beach                                            = 0x0005,
        Desert                                           = 0x0006,
        Snow                                             = 0x0007,
        Swamp                                            = 0x0008,
        Sector_1_Train_Station                           = 0x0009,
        Reactor_1                                        = 0x000A,
        Reactor_1_Core                                   = 0x000B,
        Reactor_1_Entrance                               = 0x000C,
        Sector_4_Subway                                  = 0x000D,
        Nibel_Caves_or_AForest_Caves                     = 0x000E,
        Shinra_HQ                                        = 0x000F,
        Midgar_Raid_Subway                               = 0x0010,
        Hojos_Lab                                        = 0x0011,
        Shinra_Elevators                                 = 0x0012,
        Shinra_Roof                                      = 0x0013,
        Midgar_Highway                                   = 0x0014,
        Wutai_Pagoda                                     = 0x0015,
        Church                                           = 0x0016,
        Coral_Valley                                     = 0x0017,
        Midgar_Slums                                     = 0x0018,
        Sector_4_Corridors_or_Junon_Path                 = 0x0019,
        Sector_4_Gantries_or_Midgar_Underground          = 0x001A,
        Sector_7_Support_Pillar_Stairway                 = 0x001B,
        Sector_7_Support_Pillar_Top                      = 0x001C,
        Sector_8                                         = 0x001D,
        Sewers                                           = 0x001E,
        Mythril_Mines                                    = 0x001F,
        Northern_CraterFloating_Platforms                = 0x0020,
        Corel_Mountain_Path                              = 0x0021,
        Junon_Beach                                      = 0x0022,
        Junon_Cargo_Ship                                 = 0x0023,
        Corel_Prison                                     = 0x0024,
        Battle_Square                                    = 0x0025,
        Da_ChaoRapps_Battle                              = 0x0026,
        Cids_Backyard                                    = 0x0027,
        Final_Descent_to_Sephiroth                       = 0x0028,
        Reactor_5_Entrance                               = 0x0029,
        Temple_of_the_AncientsEscher_Room                = 0x002A,
        Shinra_Mansion                                   = 0x002B,
        Junon_Airship_Dock                               = 0x002C,
        Whirlwind_Maze                                   = 0x002D,
        Junon_Underwater_Reactor                         = 0x002E,
        Gongaga_Reactor                                  = 0x002F,
        Gelnika                                          = 0x0030,
        Train_Graveyard                                  = 0x0031,
        Great_Glacier_Ice_Caves_Gaea_CliffsInside        = 0x0032,
        Sister_Ray                                       = 0x0033,
        Sister_Ray_Base                                  = 0x0034,
        Forgotten_City_Altar                             = 0x0035,
        Northern_CraterInitial_Descent                   = 0x0036,
        Northern_CraterHatchery                          = 0x0037,
        Northern_CraterWater_Area                        = 0x0038,
        Safer_Battle                                     = 0x0039,
        Kalm_FlashbackDragon_Battle                      = 0x003A,
        Junon_Underwater_Pipe                            = 0x003B,
        Corel_RailwayCanyon                              = 0x003D,
        Whirlwind_MazeCrater                             = 0x003E,
        Corel_RailwayRollercoaster                       = 0x003F,
        Wooden_Bridge                                    = 0x0040,
        Da_Chao                                          = 0x0041,
        Fort_Condor                                      = 0x0042,
        Dirt_Wasteland                                   = 0x0043,
        Bizarro_BattleRight_Side                         = 0x0044,
        Bizarro_BattleLeft_Side                          = 0x0045,
        Jenova_SYNTHESIS_Battle                          = 0x0046,
        Corel_Train_Battle                               = 0x0047,
        Cosmo_Canyon                                     = 0x0048,
        Caverns_of_the_Gi                                = 0x0049,
        Nibelheim_Mansion_Basement                       = 0x004A,
        Temple_of_the_AncientsDemons_Gate                = 0x004B,
        Temple_of_the_AncientsMural_Room                 = 0x004C,
        Temple_of_the_AncientsClock_Passage              = 0x004D,
        Final_BattleSephiroth                            = 0x004E,
        Jungle                                           = 0x004F,
        Ultimate_WeaponBattle_on_Highwind                = 0x0050,
        Corel_Reactor                                    = 0x0051,
        Unused                                           = 0x0052,
        Don_Corneos_Mansion                              = 0x0053,
        Emerald_Weapon_Battle                            = 0x0054,
        Reactor_5                                        = 0x0055,
        Shinra_HQEscape                                  = 0x0056,
        Ultimate_WeaponGongaga_Reactor                   = 0x0057,
        Corel_PrisonDyne_Battle                          = 0x0058,
        Ultimate_WeaponForest                            = 0x0059
    }

    public enum Layout { 
        Normal           = 0x00,
        Preemptive       = 0x01,
        Back             = 0x02,
        Side             = 0x03,
        Both_Sides       = 0x04,
        Second_Both_Side = 0x05,
        Second_Side      = 0x06,
        Thirday_Side     = 0x07,
        Lock_Change      = 0x08
    }
}
